name: Terraform Plan
description: Run terraform plan using Azure SP

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}
    - run: terraform init
    - run: terraform validate
    - run: terraform plan

inputs:
  terraform_version:
    required: false
    default: "1.7.5"
